
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: anurag-dev
spec: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: anurag-app
  name: anurag-app
  namespace: anurag-dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: anurag-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: anurag-app
    spec:
      containers:
      - image: dockerashu/ashumobiwebapp:6
        name: ashumobiwebapp
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: anuragsvc
  name: anuragsvc
  namespace: anurag-dev
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: anurag-app
  type: NodePort
status:

  loadBalancer: {}
